/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "gray-900": "hsl(var(--gray-900))",
        "gray-800": "hsl(var(--gray-800))",
        "gray-700": "hsl(var(--gray-700))",
        "gray-600": "hsl(var(--gray-600))",
        "gray-500": "hsl(var(--gray-500))",
        "gray-400": "hsl(var(--gray-400))",
        "gray-300": "hsl(var(--gray-300))",
        "gray-200": "hsl(var(--gray-200))",
        "gray-100": "hsl(var(--gray-100))",
        "gray-50": "hsl(var(--gray-50))",
        "primary-900": "hsl(var(--primary-900))",
        "primary-800": "hsl(var(--primary-800))",
        "primary-700": "hsl(var(--primary-700))",
        "primary-600": "hsl(var(--primary-600))",
        "primary-500": "hsl(var(--primary-500))",
        "primary-400": "hsl(var(--primary-400))",
        "primary-300": "hsl(var(--primary-300))",
        "primary-200": "hsl(var(--primary-200))",
        "primary-100": "hsl(var(--primary-100))",
        "secondary-900": "hsl(var(--secondary-900))",
        "secondary-800": "hsl(var(--secondary-800))",
        "secondary-700": "hsl(var(--secondary-700))",
        "secondary-600": "hsl(var(--secondary-600))",
        "secondary-500": "hsl(var(--secondary-500))",
        "secondary-400": "hsl(var(--secondary-400))",
        "secondary-300": "hsl(var(--secondary-300))",
        "secondary-200": "hsl(var(--secondary-200))",
        "secondary-100": "hsl(var(--secondary-100))",
        "success-900": "hsl(var(--success-900))",
        "success-800": "hsl(var(--success-800))",
        "success-700": "hsl(var(--success-700))",
        "success-600": "hsl(var(--success-600))",
        "success-500": "hsl(var(--success-500))",
        "success-400": "hsl(var(--success-400))",
        "success-300": "hsl(var(--success-300))",
        "success-200": "hsl(var(--success-200))",
        "success-100": "hsl(var(--success-100))",
        "warning-900": "hsl(var(--warning-900))",
        "warning-800": "hsl(var(--warning-800))",
        "warning-700": "hsl(var(--warning-700))",
        "warning-600": "hsl(var(--warning-600))",
        "warning-500": "hsl(var(--warning-500))",
        "warning-400": "hsl(var(--warning-400))",
        "warning-300": "hsl(var(--warning-300))",
        "warning-200": "hsl(var(--warning-200))",
        "warning-100": "hsl(var(--warning-100))",
        "danger-900": "hsl(var(--danger-900))",
        "danger-800": "hsl(var(--danger-800))",
        "danger-700": "hsl(var(--danger-700))",
        "danger-600": "hsl(var(--danger-600))",
        "danger-500": "hsl(var(--danger-500))",
        "danger-400": "hsl(var(--danger-400))",
        "danger-300": "hsl(var(--danger-300))",
        "danger-200": "hsl(var(--danger-200))",
        "danger-100": "hsl(var(--danger-100))",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },

      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
