import { ICategory, ICoursePartial } from "./types/course/index.ts";
import { IUserPartial } from "./types/user/index.ts";

export const categories: ICategory[] = [
  {
    id: "1",
    name: "Label",
    path: "courses/label",
    iconId: "Cpu",
    totalCourses: 63476,
  },
  {
    id: "2",
    name: "Business",
    path: "courses/business",
    iconId: "Handshake",
    totalCourses: 52822,
  },
  {
    id: "3",
    name: "Finance & Accounting",
    path: "courses/finance-accounting",
    iconId: "CreditCard",
    totalCourses: 33841,
  },
  {
    id: "4",
    name: "IT & Software",
    path: "courses/it-software",
    iconId: "ChartBarHorizontal",
    totalCourses: 33841,
  },
  {
    id: "5",
    name: "Personal Development",
    path: "courses/personal-development",
    iconId: "BugDroid",
    totalCourses: 20126,
  },
  {
    id: "6",
    name: "Office Productivity",
    path: "courses/office-productivity",
    iconId: "Receipt",
    totalCourses: 13932,
  },
  {
    id: "7",
    name: "Marketing",
    path: "courses/marketing",
    iconId: "MegaphoneSimple",
    totalCourses: 12068,
  },
  {
    id: "8",
    name: "Photography & Video",
    path: "courses/photography-video",
    iconId: "Camera",
    totalCourses: 6196,
  },
  {
    id: "9",
    name: "Lifestyle",
    path: "courses/lifestyle",
    iconId: "Package",
    totalCourses: 2736,
  },
  {
    id: "10",
    name: "Design",
    path: "courses/design",
    iconId: "PenNib",
    totalCourses: 2600,
  },
  {
    id: "11",
    name: "Health & Fitness",
    path: "courses/data-analytics",
    iconId: "FirstAidKit",
    totalCourses: 1678,
  },
  {
    id: "12",
    name: "Music",
    path: "courses/music",
    iconId: "Headphones",
    totalCourses: 959,
  },
];

export const users: IUserPartial[] = [
  {
    id: "1",
    firstName: "Vako",
    lastName: "Shvili",
    email: "vakoshvili@gmail.com",
    phoneNumber: "7999797979",
    password: "**********",
    passwordChangedAt: undefined,
    role: "INSTRUCTOR",
    biography: "Web Designer & Best-Selling Instructor",
    socialProfiles: undefined,
    profilePicture:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862573/lmsGenie%20assets/user/user1_lvbj0z.jpg",
    slug: "vako-shvili",
    rating: 5,
    totalStudents: 0,
    enrolledCourses: undefined,
    wishlist: undefined,
    isActive: true,
    isEmailVerified: true,
    loginCount: 100,
  },
  {
    id: "2",
    firstName: "Alex",
    lastName: "Chem",
    email: "alex@gmail.com",
    phoneNumber: "7999797979",
    password: "**********",
    passwordChangedAt: undefined,
    role: "INSTRUCTOR",
    biography: "Web Designer & Best-Selling Instructor",
    socialProfiles: undefined,
    profilePicture:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862572/lmsGenie%20assets/user/user4_qp6e9h.jpg",
    slug: "alex-chem",
    rating: 5,
    totalStudents: 0,
    enrolledCourses: undefined,
    wishlist: undefined,
    isActive: true,
    isEmailVerified: true,
    loginCount: 100,
  },
  {
    id: "3",
    firstName: "Shivani",
    lastName: "Kumari",
    email: "shivani@gmail.com",
    phoneNumber: "7999797979",
    password: "**********",
    passwordChangedAt: undefined,
    role: "INSTRUCTOR",
    biography: "Web Designer & Best-Selling Instructor",
    socialProfiles: undefined,
    profilePicture:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862571/lmsGenie%20assets/user/user2_cysjyo.jpg",
    slug: "shivani-kumari",
    rating: 5,
    totalStudents: 0,
    enrolledCourses: undefined,
    wishlist: undefined,
    isActive: true,
    isEmailVerified: true,
    loginCount: 100,
  },
  {
    id: "4",
    firstName: "Rahul",
    lastName: "Awasthi",
    email: "rahul@gmail.com",
    phoneNumber: "7999797979",
    password: "**********",
    passwordChangedAt: undefined,
    role: "INSTRUCTOR",
    biography: "Web Designer & Best-Selling Instructor",
    socialProfiles: undefined,
    profilePicture:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862570/lmsGenie%20assets/user/user3_qhjpmu.jpg",
    slug: "rahul-awasthi",
    rating: 5,
    totalStudents: 0,
    enrolledCourses: undefined,
    wishlist: undefined,
    isActive: true,
    isEmailVerified: true,
    loginCount: 100,
  },
  {
    id: "5",
    firstName: "Jitendra",
    lastName: "Thakur",
    email: "jitu@gmail.com",
    phoneNumber: "7999797979",
    password: "**********",
    passwordChangedAt: undefined,
    role: "INSTRUCTOR",
    biography: "Web Designer & Best-Selling Instructor",
    socialProfiles: undefined,
    profilePicture:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862570/lmsGenie%20assets/user/user3_qhjpmu.jpg",
    slug: "jitendra-thakur",
    rating: 5,
    totalStudents: 0,
    enrolledCourses: undefined,
    wishlist: undefined,
    isActive: true,
    isEmailVerified: true,
    loginCount: 100,
  },
];

export const courses: ICoursePartial[] = [
  {
    id: "1",
    category: ["FINANCE AND ACCOUNTING"],
    thumbnail:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862207/lmsGenie%20assets/course/course6_tclpvl.jpg",
    totalEnrollments: 500,
    listPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 500,
    },
    discountedPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 400,
    },
    discountPercentage: 10,
    averageRating: 5,
    title: "The Complete Personal Finance Course: Save, Protect, Make More",
    instructors: [
      {
        id: "1",
        firstName: "Vako",
        lastName: "Shvili",
        email: "vakoshvili@gmail.com",
        phoneNumber: "7999797979",
        password: "**********",
        passwordChangedAt: undefined,
        role: "INSTRUCTOR",
        biography: "Web Designer & Best-Selling Instructor",
        socialProfiles: undefined,
        profilePicture:
          "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862573/lmsGenie%20assets/user/user1_lvbj0z.jpg",
        slug: "vako-shvili",
        rating: 5,
        totalStudents: 0,
        enrolledCourses: undefined,
        wishlist: undefined,
        isActive: true,
        isEmailVerified: true,
        loginCount: 100,
      },
    ],
  },
  {
    id: "2",
    category: ["LIFE STYLE"],
    thumbnail:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862205/lmsGenie%20assets/course/course1_p9jghe.jpg",
    totalEnrollments: 500,
    listPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 500,
    },
    discountedPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 400,
    },
    discountPercentage: 10,
    averageRating: 5,
    title: "Transformation Life Coach Certification (Accredited)",
    instructors: [
      {
        id: "1",
        firstName: "Vako",
        lastName: "Shvili",
        email: "vakoshvili@gmail.com",
        phoneNumber: "7999797979",
        password: "**********",
        passwordChangedAt: undefined,
        role: "INSTRUCTOR",
        biography: "Web Designer & Best-Selling Instructor",
        socialProfiles: undefined,
        profilePicture:
          "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862573/lmsGenie%20assets/user/user1_lvbj0z.jpg",
        slug: "vako-shvili",
        rating: 5,
        totalStudents: 0,
        enrolledCourses: undefined,
        wishlist: undefined,
        isActive: true,
        isEmailVerified: true,
        loginCount: 100,
      },
    ],
  },
  {
    id: "3",
    category: ["BUSINESS"],
    thumbnail:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862198/lmsGenie%20assets/course/course4_zzetiz.jpg",
    totalEnrollments: 500,
    listPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 500,
    },
    discountedPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 400,
    },
    discountPercentage: 10,
    averageRating: 5,
    title:
      "Learn Python Programming Masterclass dehudheudheuhdeudhdddddddddddddddddddddddd dehudheudheuhdeudhdddddddddddddddddddddddd dehudheudheuhdeudhdddddddddddddddddddddddd",
    instructors: [
      {
        id: "1",
        firstName: "Vako",
        lastName: "Shvili",
        email: "vakoshvili@gmail.com",
        phoneNumber: "7999797979",
        password: "**********",
        passwordChangedAt: undefined,
        role: "INSTRUCTOR",
        biography: "Web Designer & Best-Selling Instructor",
        socialProfiles: undefined,
        profilePicture:
          "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862573/lmsGenie%20assets/user/user1_lvbj0z.jpg",
        slug: "vako-shvili",
        rating: 5,
        totalStudents: 0,
        enrolledCourses: undefined,
        wishlist: undefined,
        isActive: true,
        isEmailVerified: true,
        loginCount: 100,
      },
    ],
  },
  {
    id: "4",
    category: ["BUSINESS"],
    thumbnail:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862197/lmsGenie%20assets/course/course2_zh4bxx.jpg",
    totalEnrollments: 500,
    listPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 500,
    },
    discountedPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 400,
    },
    discountPercentage: 10,
    averageRating: 5,
    title: "Business Model Innovation: Differentiate & Grow Your Company",
    instructors: [
      {
        id: "1",
        firstName: "Vako",
        lastName: "Shvili",
        email: "vakoshvili@gmail.com",
        phoneNumber: "7999797979",
        password: "**********",
        passwordChangedAt: undefined,
        role: "INSTRUCTOR",
        biography: "Web Designer & Best-Selling Instructor",
        socialProfiles: undefined,
        profilePicture:
          "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862573/lmsGenie%20assets/user/user1_lvbj0z.jpg",
        slug: "vako-shvili",
        rating: 5,
        totalStudents: 0,
        enrolledCourses: undefined,
        wishlist: undefined,
        isActive: true,
        isEmailVerified: true,
        loginCount: 100,
      },
    ],
  },
  {
    id: "5",
    category: ["MUSIC"],
    thumbnail:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862197/lmsGenie%20assets/course/course10_dwwbdy.jpg",
    totalEnrollments: 500,
    listPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 500,
    },
    discountedPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 400,
    },
    discountPercentage: 10,
    averageRating: 5,
    title: "Pianoforall - Incredible New Way To Learn Piano & Keyboard",
    instructors: [
      {
        id: "1",
        firstName: "Vako",
        lastName: "Shvili",
        email: "vakoshvili@gmail.com",
        phoneNumber: "7999797979",
        password: "**********",
        passwordChangedAt: undefined,
        role: "INSTRUCTOR",
        biography: "Web Designer & Best-Selling Instructor",
        socialProfiles: undefined,
        profilePicture:
          "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862573/lmsGenie%20assets/user/user1_lvbj0z.jpg",
        slug: "vako-shvili",
        rating: 5,
        totalStudents: 0,
        enrolledCourses: undefined,
        wishlist: undefined,
        isActive: true,
        isEmailVerified: true,
        loginCount: 100,
      },
    ],
  },
  {
    id: "6",
    category: ["BUSINESS"],
    thumbnail:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862197/lmsGenie%20assets/course/course8_usweyy.jpg",
    totalEnrollments: 500,
    listPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 500,
    },
    discountedPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 400,
    },
    discountPercentage: 10,
    averageRating: 5,
    title: "Business Model Innovation: Differentiate & Grow Your Company",
    instructors: [
      {
        id: "1",
        firstName: "Vako",
        lastName: "Shvili",
        email: "vakoshvili@gmail.com",
        phoneNumber: "7999797979",
        password: "**********",
        passwordChangedAt: undefined,
        role: "INSTRUCTOR",
        biography: "Web Designer & Best-Selling Instructor",
        socialProfiles: undefined,
        profilePicture:
          "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862573/lmsGenie%20assets/user/user1_lvbj0z.jpg",
        slug: "vako-shvili",
        rating: 5,
        totalStudents: 0,
        enrolledCourses: undefined,
        wishlist: undefined,
        isActive: true,
        isEmailVerified: true,
        loginCount: 100,
      },
    ],
  },
  {
    id: "7",
    category: ["MUSIC"],
    thumbnail:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862194/lmsGenie%20assets/course/course9_o73qqh.jpg",
    totalEnrollments: 500,
    listPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 500,
    },
    discountedPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 400,
    },
    discountPercentage: 10,
    averageRating: 5,
    title: "Pianoforall - Incredible New Way To Learn Piano & Keyboard",
    instructors: [
      {
        id: "1",
        firstName: "Vako",
        lastName: "Shvili",
        email: "vakoshvili@gmail.com",
        phoneNumber: "7999797979",
        password: "**********",
        passwordChangedAt: undefined,
        role: "INSTRUCTOR",
        biography: "Web Designer & Best-Selling Instructor",
        socialProfiles: undefined,
        profilePicture:
          "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862573/lmsGenie%20assets/user/user1_lvbj0z.jpg",
        slug: "vako-shvili",
        rating: 5,
        totalStudents: 0,
        enrolledCourses: undefined,
        wishlist: undefined,
        isActive: true,
        isEmailVerified: true,
        loginCount: 100,
      },
    ],
  },
  {
    id: "8",
    category: ["IT & SOFTWARE"],
    thumbnail:
      "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862193/lmsGenie%20assets/course/course3_ywumwu.jpg",
    totalEnrollments: 500,
    listPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 500,
    },
    discountedPrice: {
      currencyCode: "USD",
      currencyName: "us",
      currencySymbol: "$",
      price: 400,
    },
    discountPercentage: 10,
    averageRating: 5,
    title:
      "Learn Python Programming Masterclass dehudheudheuhdeudhdddddddddddddddddddddddd dehudheudheuhdeudhdddddddddddddddddddddddd dehudheudheuhdeudhdddddddddddddddddddddddd",
    instructors: [
      {
        id: "1",
        firstName: "Vako",
        lastName: "Shvili",
        email: "vakoshvili@gmail.com",
        phoneNumber: "7999797979",
        password: "**********",
        passwordChangedAt: undefined,
        role: "INSTRUCTOR",
        biography: "Web Designer & Best-Selling Instructor",
        socialProfiles: undefined,
        profilePicture:
          "https://res.cloudinary.com/lmsgenie-storage/image/upload/v1694862573/lmsGenie%20assets/user/user1_lvbj0z.jpg",
        slug: "vako-shvili",
        rating: 5,
        totalStudents: 0,
        enrolledCourses: undefined,
        wishlist: undefined,
        isActive: true,
        isEmailVerified: true,
        loginCount: 100,
      },
    ],
  },
];

export const FAQS = [
  {
    id: "74114cdc-b545-415e-9aac-bcb865a94200",
    heading: "FAQs section 1",
    faqs: [
      {
        id: "64d79924-3699-475a-b9d1-e4f9d3702df1",
        question: "What is the best way to learn?",
        answer:
          "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sit, maxime! Praesentium, adipisci. Eos vitae ea corporis dolorem debitis id voluptates.",
      },
      {
        id: "cdd9f4d2-73c4-4bd1-8e34-4c4b2c46a30a",
        question: "What is the best way to learn?",
        answer:
          "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur cumque ratione accusamus. Magnam non adipisci veniam necessitatibus nobis esse vel fuga, error dolor quaerat inventore labore sequi rerum ullam earum?",
      },
      {
        id: "924d25c1-21bd-4b54-906d-671a7d3e33d7",
        question: "What is the best way to learn?",
        answer:
          "Lorem, ipsum dolor sit amet consectetur adipisicing elit. In iste dolorem illum quasi assumenda vero esse laudantium, culpa magni, alias aliquid doloremque, explicabo nisi accusamus ab ipsum.",
      },
      {
        id: "c3d07eb4-ea76-4826-ae0c-abadab46ae84",
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: "4856f987-016f-4a8b-8d66-db4e6ecced56",
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: "8c4ad33a-172b-45e0-8f1c-228b7e012e10",
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: "10199e4c-2c38-460d-a83f-93f041b0a49b",
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: "952ce431-8b92-48c0-9383-2a9a743f4170",
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: "3ff964fc-3c30-4d08-9718-75d7e2bf113a",
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: "54961634-b387-4206-a6ae-2964d501a6c8",
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: "da860353-163b-4662-95ee-fdc0b4a61364",
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: "f9106f21-29e0-4ea2-8bf0-cd1a1e2a258c",
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: "0cfaa481-2902-4fd5-b4ed-8330445a4dbf",
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: "c07829b1-3303-4d87-9559-e0813146f6d7",
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
    ],
  },
  {
    id: "40996f66-a9a1-40e5-97f1-c251ee246d38",
    heading: "FAQs section 2",
    faqs: [
      {
        id: "bd875d9b-e3bc-48b4-b879-e0ecbb7e7970",
        question: "What is the best way to learn new?",
        answer:
          "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sit, maxime! Praesentium, adipisci. Eos vitae ea corporis dolorem debitis id voluptates.",
      },
      {
        id: "97b80f52-7243-4365-8533-d73e84167e2b",
        question: "What is the best way to learn?",
        answer:
          "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur cumque ratione accusamus. Magnam non adipisci veniam necessitatibus nobis esse vel fuga, error dolor quaerat inventore labore sequi rerum ullam earum?",
      },
    ],
  },
  {
    id: "0f1ebade-e59e-44f6-b9d4-66c87e771c75",
    heading: "FAQs section 3",
    faqs: [
      {
        id: "acb79d9d-9b44-4a2c-b452-1011b16f8789",
        question: "What is the best way to learn?",
        answer:
          "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sit, maxime! Praesentium, adipisci. Eos vitae ea corporis dolorem debitis id voluptates.",
      },
      {
        id: "0b073a23-6412-4579-a9f0-3c49650fb703",
        question: "What is the best way to learn?",
        answer:
          "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur cumque ratione accusamus. Magnam non adipisci veniam necessitatibus nobis esse vel fuga, error dolor quaerat inventore labore sequi rerum ullam earum?",
      },
      {
        id: "49a6d036-6bf2-4f37-bfbe-7e4be0555dde",
        question: "What is the best way to learn?",
        answer:
          "Lorem, ipsum dolor sit amet consectetur adipisicing elit. In iste dolorem illum quasi assumenda vero esse laudantium, culpa magni, alias aliquid doloremque, explicabo nisi accusamus ab ipsum.",
      },
      {
        id: window.crypto.randomUUID(),
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: window.crypto.randomUUID(),
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: window.crypto.randomUUID(),
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: window.crypto.randomUUID(),
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: window.crypto.randomUUID(),
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: window.crypto.randomUUID(),
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: window.crypto.randomUUID(),
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: window.crypto.randomUUID(),
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: window.crypto.randomUUID(),
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: window.crypto.randomUUID(),
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
      {
        id: window.crypto.randomUUID(),
        question: "What is the best way to learn?",
        answer: "The best way to learn is to practice and practice.",
      },
    ],
  },
];
